spring:
  application:
    name: Observabilty

server:
  port: 8086

cloud:
  aws:
    region:
      static: "us-east-2"
    credentials:
      secret-key: "here"
      access-key: "akhere"

application:
  bucket-name: "s3-accountb"